version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: shp_prometheus
    restart: always
    ports:
      - 5001:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: shp_grafana
    restart: always
    ports:
      - 5002:3000
