version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Ljubljana'
      WEBPASSWORD: 'delavnica'
    # Volumes store your data between container upgrades
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq:
